### PR TITLE
Add param profile to hide author in post

### LINKED ISSUE #867: Hide author name and image in post?
### Question

I'd like to hide the author image and name for all posts. Since it is my site/blog, it is kind of obvious that the posts were by me.
Is there a way (frontmatter? `_index.md`? ...?) to hide it?

I've seen other themes that support the `profile: false` in the front matter, but that does not seem to work for this theme. 
I'm sure I can change it in my own fork of the theme, but maybe there is a simple, standard way to do it.

Thanks!

### PR DESCRIPTION
**Pull request by BernatBC**
### Issue
Hide author name and image in post? Fixes #867

### Description
Added the possibility to hide author in post by setting the parameter:
```yaml
profile: false #defaults true
```
I know this is not the most elegant solution (I had to add vertical gap).

### Test Evidence
`profile: true` (or no `profile` set):
image

`profile: false`:
image

### CODE REVIEW

**Comment by hossainemruz** [comment]
Thank you @BernatBC! I think the configuration should go under `params.features.blog`. We can do something similar to this:
```yaml
params:
  features:
    blog:
      showAuthor: false
```

**Comment by BernatBC** [comment]
Ok, I just changed the parameter localization to:
```yaml
params:
  features:
    blog:
      showAuthor: false
```

**Comment by hossainemruz** [comment]
Thank you. I will test the changes specially on mobile device.

**Comment by dietervansteenwegen** [comment]
> Thank you. I will test the changes specially on mobile device.

Just to make sure I understand, you will test the changes on a mobile device because the 80 pixels spacing is hard-coded and thus not relative to the screen size/rendering? Or not?

**Comment by hossainemruz** [comment]
> > Thank you. I will test the changes specially on mobile device.
> 
> Just to make sure I understand, you will test the changes on a mobile device because the 80 pixels spacing is hard-coded and thus not relative to the screen size/rendering? Or not?

Yes. I will check on mobile and Tablet.

**Review by hossainemruz — APPROVED** [review]

**Pull request merged**
