### PR TITLE
Support Cloudflare Web Analytics

### PR DESCRIPTION
**Pull request by linzeyan**

### CODE REVIEW

**Comment by hossainemruz** [comment]
Hi @linzeyan, sorry for late replay. Can you please point me to the resource that you followed for adding this analytics? That will help me to verify the changes.

Also, please add example configure here: https://github.com/hugo-toha/toha/blob/0afcdcd468f6b03671cd7a624872646049f7fb0c/exampleSite/config.yaml#L153

**Comment by linzeyan** [comment]
> 

https://github.com/hugo-toha/toha/blob/0afcdcd468f6b03671cd7a624872646049f7fb0c/layouts/partials/analytics.html#L45
```diff
                var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
                g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
            })();
            </script>
        {{ end }}
+
+       {{ with .cloudflare }}
+           <!-- Cloudflare Web Analytics -->
+           <script defer src='https://static.cloudflareinsights.com/beacon.min.js'
+               data-cf-beacon='{"token": "{{ .token }}"}'
+           ></script>
+           <!-- End Cloudflare Web Analytics -->
        {{ end }}
```

- reference： https://developers.cloudflare.com/analytics/faq/web-analytics/#setup


https://github.com/hugo-toha/toha/blob/0afcdcd468f6b03671cd7a624872646049f7fb0c/exampleSite/config.yaml#L153

```diff
    analytics:
      enabled: false
      services:
+       # cloudflare web analytics
+       cloudflare:
+         token: "<token>"
        # Google Analytics
        google:
          id: G-H4LBG7NDFZ
        # # CounterDev
        # counterDev:
        #   id: <your counterdev id>
```

**Comment by hossainemruz** [comment]
Hi @linzeyan! For some reason, I don't see the changes in `exampleSite/config.yaml` file. Can you please make sure that you have pushed the change?

**Comment by linzeyan** [comment]
Hi @hossainemruz, I pushed the changes, thanks for your reminder.

**Review by hossainemruz — APPROVED** [review]
Thank you @linzeyan

**Pull request merged**
