### PR TITLE
Allow setting GIFS as author image

### PR DESCRIPTION
**Pull request by Rihoj**
### Issue
fixes hugo-toha/toha#392
fixes hugo-toha/toha#209

### Description

allow_gifs -  don't apply image processing to svg or gif

### Test Evidence

Add a gif as a author image, and make sure it displays as expected on home page as well as single posts or anywhere else the author image is used.

### CODE REVIEW

**Review by hossainemruz — APPROVED** [review]
Thank you @Rihoj

**Comment by Rihoj** [comment]
Glad to be of help @hossainemruz !

**Comment by talves** [comment]
I believe this PR broke your theme. The assignment syntax "=" is incorrect from what I can tell. I don't have time to make an issue, because I'm not actually using the theme, but wanted to give you a heads up.

**Comment by Rihoj** [comment]
@talves I will take a look when I can. Thank you for letting me know

**Comment by talves** [comment]
Remember when short declaration operator and trying to change it’s value type you would typically get an error. I think there's something going on with that here in the code. It may have always been there.

https://golangdocs.com/short-variable-declaration-in-golang

**Pull request merged**
