### PR TITLE
Bundle CSS with Hugo's Sass feature

### PR DESCRIPTION
**Pull request by aq1018**
### Issue

We should bundle all CSS to increase site performance.

Hugo offers an easy way to bundle css via [Hugo's Sass Pipeline](https://gohugo.io/hugo-pipes/scss-sass/)

This PR migrates css files to a css bundle. This is part 2 of #702.

### Test Evidence

Same as #702, I did it incrementally while checking against https://github.com/hugo-toha/hugo-toha.github.io

### CODE REVIEW

**Comment by hossainemruz** [comment]
Hi @aq1018. Since the JS PR has been merged, we can go ahead with this PR. Rebase this PR against main and make any change if you need. Do it at your own pace. No rush from me. Just let me know when it is ready.

**Comment by aq1018** [comment]
@hossainemruz rebased!

**Review by hossainemruz — APPROVED** [review]

**Comment by hossainemruz** [comment]
Hi @aq1018, I might like to change few things. Since, I don't have any push access to this PR, I am going to merge it and open subsequent PR with the changes. I will let you know what changes.

**Comment by aq1018** [comment]
I can add you to my branch if it makes it easier for you :) Just let me know.

**Comment by aq1018** [comment]
Oh I see you already merged. NVM... If you need any help, just ping me!

**Comment by hossainemruz** [comment]
For now, everything works fine. So, no rush on the changes. I am going do the changes over time.

I have also updated the usage instructions. Users should be able to use this theme from `main` branch.

**Pull request merged**
