### PR TITLE
Academic career section

### PR DESCRIPTION
**Pull request by ChapChap**
Hi Emruz Hossain 👋 ,

This PR is my clumsy attempt to add a new section : School Career 👨‍🎓 .

I mostly copy-paste from Experiences but wanted the lines to be aligned left.

I am not a dev and even less an UI Designer so please feel free to change whatever you want to 😉 .

Data model
```yaml
studies:
- degree: <String>
  school:
    name: <String>
    location: <String>
  start: <String>
  end: <String>
  lessons: list(<String>)
```

Chap 🤖

### CODE REVIEW

**Comment by blueyetisoftware** [comment]
@ChapChap Have you tried this instead of making a new type

**Comment by ChapChap** [comment]
No I wanted a different display from experiences.
Plus the horizontal bars are messed up if the previous experience count is odd...

**Comment by ChapChap** [comment]
Removing `.lessons` may look a little better

**Comment by hossainemruz** [comment]
We have to come up with a better design. Let's call it `Academic Career`. Whats info does matter for this section?
- Degree
- Institution
- Timeline
- GCPA
- Taken courses
- Extracurricular activity

Anything else?

**Comment by ChapChap** [comment]
OK for `Academic Carrer`

And I think the essentials are
- Degree
- Institution
- Timeline
And the optionals
- GCPA
- Taken courses
- Extracurricular activity
I think that's it to keep it simple.

UI speaking, replacing the circles with a minimal graduate cap or a certificate with the same color of the lines may be nice.

**Comment by hossainemruz** [comment]
I am planning to do a different UI. Will try to do a mockup and get you back as soon as possible.

**Comment by blueyetisoftware** [comment]
Being able to add icons into the circles rather than a number would be nice. Each section could optionally define an icon that would go in the circle. An icon font would allow people to easily switch between numbers and icons. It would be similar to the font awesome icons used in the 'about' section.

**Comment by p-vernaeckt** [comment]
Hi @hossainemruz ! Any progress on this PR?

**Comment by hossainemruz** [comment]
No. We need a better design for academic section.

**Comment by p-vernaeckt** [comment]
The linear design mentioned earlier with the additional subitems wasn't enough?

**Comment by hossainemruz** [comment]
When this PR was created, I had different visual in mind. Unfortunately, I didn't get time to implement the design. So, this PR was never completed.

**Comment by p-vernaeckt** [comment]
I see...I would love to help, but I'm far from being qualified for this task 😢

**Comment by hossainemruz** [comment]
I will try to come up with design with the essential elements pointed by @ChapChap [here](https://github.com/hossainemruz/toha/pull/25#issuecomment-652273931). Anything else you think important @p-vernaeckt ?

**Comment by p-vernaeckt** [comment]
No, these items fit my needs really well, as long as all the items are optionals ;)

**Comment by hossainemruz** [comment]
What do  you guys think about this design? cc @ChapChap @phinatic @p-vernaeckt.
Education
Only institution, degree and timeline are required fields. Rest of the fields are optional. User will have the ability to chose the icons from Font Awesome. Final implementation should look better with theme's color scheme.

**Comment by p-vernaeckt** [comment]
It contrasts a lot, maybe too much with what's currently in Toha

**Comment by hossainemruz** [comment]
Yes @p-vernaeckt. It just a rough estimation of what it will look like. The contrasts should be fixed after applying theme CSS. I am not a designer. :P

**Comment by hossainemruz** [comment]
@p-vernaeckt  Does it look better now?

**Comment by p-vernaeckt** [comment]
> @p-vernaeckt Does it look better now?

You didn't posted the screenshot ^^



> Yes @p-vernaeckt. It just a rough estimation of what it will look like. The contrasts should be fixed after applying theme CSS.

By contrast I mean it's very different from the rest of toha, it might look a bit odd.

**Comment by hossainemruz** [comment]
Probably this has little more simplicity.
Education2

**Comment by ipankajsingh** [comment]
> 
> 
> Probably this has little more simplicity.
> Education2

This looks so much better, probalbly border-radius of 2px will make it more appealing, too much of sharp edges otherwise.

**Comment by ipankajsingh** [comment]
> 
> 
> Probably this has little more simplicity.
> Education2

Also, it will look better if we don't include the top and bottom lines.
The vertical line which is after "2016-2020" and the vertical line which is before "2005-2010."
Because those lines aren't coming from anywhere nor going anywhere, it will make the UI more clean

**Comment by hossainemruz** [comment]
@ipankajsingh here you go...
Education 3

About the sharp edges. I am using lines to draw the rectangles. So, I can't show the border radius here but I can give them on the final implementation.

**Comment by ipankajsingh** [comment]
> 
> 
> @ipankajsingh here you go...
> Education 3
> 
> About the sharp edges. I am using lines to draw the rectangles. So, I can't show the border radius here but I can give them on the final implementation.

Perfect !!!

I hope all the fields inside the card on toggle basis, like if someone doesn't want to show CGPA or publications then they should be able to just leave that blank and the heading also doesn't show up.

**Comment by hossainemruz** [comment]
Yes. All the fields will be optional except Institution, degree, and timeline.

**Comment by hossainemruz** [comment]
What do you guys think about this design? The previous designs split the page into two parts. As a result the the cards can get really tall which does not looks good. This new design is more simple and solve that problem. Furthermore this is easy to work with and has better responsiveness.
Education 4

cc @p-vernaeckt @ipankajsingh

**Comment by p-vernaeckt** [comment]
Oh yes, I really like this last one!

**Comment by ipankajsingh** [comment]
> What do you guys think about this design? The previous designs split the page into two parts. As a result the the cards can get really tall which does not looks good. This new design is more simple and solve that problem. Furthermore this is easy to work with and has better responsiveness.
> Education 4
> 
> cc @p-vernaeckt @ipankajsingh

Looks good, but if I may suggest.

How about joining 1st and 2nd from left, 2nd & 3rd from right.
Something like this...

Screenshot_20201116_004058

**Comment by hossainemruz** [comment]
Here, every icon is representing the degree accomplished in the respective card. So, icon between two cards make no sense.

**Comment by ipankajsingh** [comment]
> Here, every icon is representing the degree accomplished in the respective card. So, icon between two cards make no sense.

Yeah , but if we move the icon on top, like in below screenshot then it will make sense.

The reason I am suggesting the modification is because that will make the UI more centered, all the years on left side and cards on right side is shifting the UI very much on right side and left side looks unbalanced. 

image

**Comment by ipankajsingh** [comment]
> > Here, every icon is representing the degree accomplished in the respective card. So, icon between two cards make no sense.
> 
> Yeah , but if we move the icon on top, like in below screenshot then it will make sense.
> 
> The reason I am suggesting the modification is because that will make the UI more centered, all the years on left side and cards on right side is shifting the UI very much on right side and left side looks unbalanced.
> 
> sample

@hossainemruz , how's it ?

**Comment by hossainemruz** [comment]
I don't think I am wiling to go with this design.
Education 5

**Comment by hossainemruz** [comment]
Perhaps, we can implement the both templates. Users can choose either of them.

**Comment by p-vernaeckt** [comment]
> I don't think I am wiling to go with this design.
> Education 5 (1)

I don't like it either. To me it's introducing confusion for no real gain.

**Comment by ipankajsingh** [comment]
> Perhaps, we can implement the both designs as separate templates. Users can choose either of them.

If it's not much then yeah, people will have 2 choice to choose from.
and also, DO we need to keep publications in the card ? coz we'll have dedicated publications section anyway.

**Comment by ipankajsingh** [comment]
> > I don't think I am wiling to go with this design.
> > Education 5 (1)
> 
> I don't like it either. To me it's introducing confusion for no real gain.

At 1st glance may be, but if you give it sometime, it will sink in.
The flow starts from bottom and goes all the way to the top, but yeah everyone has their own way of liking things, I like the design coz it makes the UI much centered aligned and creates a flow just like we have in experience section.
Like Emruz said, let's keep both the templates, people can choose.

**Comment by ChapChap** [comment]
I would see it more roundish as the other pieces are also round
the text cards seem really sharp towards the rest.

And maybe it would give a better rendering to justify the text left when the date bubble is to the left and justify right otherwise

**Comment by hossainemruz** [comment]
@ChapChap can you please restore the `school-career-section`? This PR was automatically closed when I tried to rebase against master. Also, please give me permission to commit in this PR.

**Comment by hossainemruz** [comment]
Give me permission to commit in this branch. I am getting this error.
```bash
 ! [remote rejected] school-career-section -> school-career-section (permission denied)
error: failed to push some refs to 'git@github.com:ChapChap/toha.git'
```

**Comment by ChapChap** [comment]
I'm sorry, I deleted the branch as I though you took modifications elsewhere.
I shall recreate the branch from latest state of master and with my custom layouts/files
Will it be ok for you ?

**Comment by hossainemruz** [comment]
Unfortunately, I was unable to re-open this PR. We had to open a new PR. Rest of the discussion will process here: #168.

**Pull request closed without merging**
