### PR TITLE
Refine rss build logic

### PR DESCRIPTION
**Pull request by Rihoj**
### Issue
When isHome was true the Recursive pages method didn't work.

### Description

@salastro @hossainemruz I am not sure why my site has the isHome variable set as false, but the section as true always, but this was the best solution I could find out there.

Because I am not confident in this please double check that the logic makes sense

### CODE REVIEW

**Comment by Rihoj** [comment]
I have my changes are also failing in a later hugo version

```
hugo v0.93.0-07469082+extended linux/amd64 BuildDate=2022-02-28T08:30:42Z VendorInfo=gohugoio
ERROR 2022/03/01 00:03:40 render of "section" failed: "/home/runner/work/rayprogramming.com/rayprogramming.com/themes/toha/layouts/_default/rss.xml:29:14": execute of template failed: template: _default/rss.xml:29:14: executing "_default/rss.xml" at <.URL>: can't evaluate field URL in type page.Page
```

**Review by hossainemruz — APPROVED** [review]
Thanks @Rihoj

**Comment by Nirzak** [comment]
But this pull request ultimately breaks the template. The template Pr doesn't getting merged and all jobs are failing @hossainemruz

**Comment by hossainemruz** [comment]
Which one are you talking about @Nirzak ?

**Comment by Nirzak** [comment]
> Which one are you talking about @Nirzak ?

About that bump theme PR generated because of this PR

**Comment by Nirzak** [comment]
Screenshot_20220301-154317
Every checks got failed and after the merge site also became down. You can also try to merge this hugo-toha.github.io and check. I think problem is with the rss

**Comment by hossainemruz** [comment]
Ah! I see. The PR looked innocent. So, I merged without testing. Opened a new issue here:https://github.com/hugo-toha/toha/issues/546. Will fix ASAP.

**Comment by Rihoj** [comment]
@Nirzak If these are the builds you are speaking of:
* [The build on your project](https://github.com/Nirzak/nirzak.github.io/runs/5371833939?check_suite_focus=true)
* [The build on hugo-toha.github.io](https://github.com/hugo-toha/hugo-toha.github.io/runs/5368926038?check_suite_focus=true)

PRs related to those builds:
* [Nirzak's pr 53](https://github.com/Nirzak/nirzak.github.io/pull/93)
* [hugo-toha.github.io 148](https://github.com/hugo-toha/hugo-toha.github.io/pull/148)

Then those builds are from before this PR. as [711d4c7](https://github.com/hugo-toha/toha/commit/711d4c774923a3134e3f3164d45c994e07c8afc3) was the giscus change. However, yes, I found out I was running on an older version of hugo which caused a break in the automated builds from the [d3b20dc](https://github.com/hugo-toha/toha/commit/d3b20dc424dc9dfaeb009dd6348e61fc1b9fd21a) commit.

This was fixed in this pr under the commit [21fabc2](https://github.com/hugo-toha/toha/pull/545/commits/21fabc210d09093d5e6253ced21b32ec6487004b)

**Pull request merged**
