### PR TITLE
Improve de.toml

### PR DESCRIPTION
**Pull request by hubitor**
### Description

I've made some improvements to de.toml. Some text was in Dutch instead of German.
I've also added .history folder in .gitignore.

### CODE REVIEW

**Comment by hossainemruz** [comment]
@hubitor Thank you for the PR. One question though. Google translator detect you changes as German language where original one detect as Dutch. What's the difference between them? It seems `de` is the ISO code for German language.

**Comment by hubitor** [comment]
@hossainemruz : Thank you for Toha! 
Yes, country ISO code of Germany is de and of Netherlands (language: Dutch) is nl. ([Country Codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes))
Like I mentioned before, there was a mix of german and dutch words in de.toml. E.g.
[Inhoudsopgave](https://www.deepl.com/translator#nl/en/Inhoudsopgave) is dutch and [Beiträge](https://www.deepl.com/translator#de/en/Beitr%C3%A4ge) is german.

**Comment by hossainemruz** [comment]
Ok. Thank you for clarification.

**Review by hossainemruz — APPROVED** [review]

**Comment by hubitor** [comment]
You're welcome!

**Pull request merged**
