### PR TITLE
Allow footer configuration

### PR DESCRIPTION
**Pull request by Kaligule**
Introduced some new configuration options. These are the default values:

```yaml
params:
  footer:
    enable: true
    navigation:
      enable: true
    contactMe:
      enable: true
    credentials:
      enable: true
  newsletter: # not new, but similar to new options
    enable: false
```

Where should the documentation go?

Please note that I am technically a web developer, but not familiar with hugo in the slightest. I am very happy about constructive feedback.

Btw it might be easier to review the commits one by one because the indentation makes the diff look more crazy than it is.

### Issue

https://github.com/hugo-toha/toha/issues/224

Doesn't solve that issue completly as it is about the footer _and the navbar_. The navbar was a bit over my head at this moment.

### Description

Allows to disable/enable parts of the footer (or all of the footer).

#### Footer disabled

Screenshot_2021-04-28_12:59:29

#### Navigation disabled

Screenshot_2021-04-28_12:58:53

#### Footer enabled, but all parts of it disabled

Screenshot_2021-04-28_12:58:14

#### Copyright notice disabled
Screenshot_2021-04-28_13:01:28

### CODE REVIEW

**Comment by hossainemruz** [comment]
@Kaligule  Thank you for the PR. I think footer should be just another section so that user can use custom template for it.

**Comment by Kaligule** [comment]
@hossainemruz I don't think I can help there. Do I understand you correctly that you do not want to merge this PR but work on your own solution? (I this case I will have to point my site to my own fork until you succeded.)

**Review by hossainemruz — APPROVED** [review]
Thanks @Kaligule . I have made little adjustment. Now, user can provide a template for the footer.

**Comment by Kaligule** [comment]
Cool, thanks :)

**Pull request merged**
