### PR TITLE
Add education section

### PR DESCRIPTION
**Pull request by hossainemruz**
Original discussion: #25

### CODE REVIEW

**Comment by hossainemruz** [comment]
Here is a screenshot of the final implemenation.
image

cc @ChapChap @phinatic @p-vernaeckt @ipankajsingh.

I will work on the second design too.

**Comment by hossainemruz** [comment]
Previous screenshot was taken after zooming out to fit all the card in one view. Probably this screenshot look better. Open the image in new tab.
image

**Comment by hossainemruz** [comment]
This is what the `education.yaml` file going to look like.
```yaml
# section information
section:
  name: Education
  id: education
  enable: true
  weight: 4
  showOnNavbar: true
  # Can optionally hide the title in sections
  # hideTitle: true 

degrees:
- name: Ph.D in Quantum Cryptography
  icon: fa-microscope
  timeframe: 2016-2020
  institution:
    name: ABC University of Technology
    url: "#"
  grade:
    scale: CGPA
    achieved: 3.6
    outOf: 4
  publications:
  - title: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    url: "#"
  - title: Fusce eu augue ut odio porttitor pulvinar.
    url: "#"
  - title: Nullam vitae orci tincidunt purus viverra pulvinar.
    url: "#"
- name: B.Sc. in Computer Science & Engineering
  icon: fa-graduation-cap
  timeframe: 2012-2016
  institution:
    name: University of XYZ
    url: "#"
  grade:
    scale: CGPA
    achieved: 3.5
    outOf: 4
  takenCourses:
    # if true, the courses will be rendered as a table otherwise it will render as a list and the grades will be hidden.
    showGrades: true
    courses:
    - name: Data Structures and Algorithm
      achieved: 3.75
      outOf: 4
    - name: Network Security
      achieved: 3.80
      outOf: 4
    - name: Operating System
      achieved: 3.5
      outOf: 4
    - name: Artificial Intelligent
      achieved: 3.75
      outOf: 4
  publications:
  - title: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    url: "#"
  - title: Fusce eu augue ut odio porttitor pulvinar.
    url: "#"
  extracurricularActivities:
  - In vitae facilisis est, eget porta sem.
  - Vestibulum consectetur lorem justo, at laoreet lorem feugiat et.
  - Duis sed massa feugiat, ornare justo et, aliquam est.
  - Pellentesque ut fringilla magna.
- name: Higher Secondary School Certificate
  icon: fa-university
  timeframe: 2010-2012
  institution:
    name: MST College of Science
    url: "#"
  grade:
    scale: GPA
    achieved: 5
    outOf: 5
  extracurricularActivities:
  - In vitae facilisis est, eget porta sem.
  - Vestibulum consectetur lorem justo, at laoreet lorem feugiat et.
  - Duis sed massa feugiat, ornare justo et, aliquam est.
  - Pellentesque ut fringilla magna.
- name: Secondary School Certificate
  icon: fa-school
  timeframe: 2005-2010
  institution:
    name: JK School of Science
  grade:
    scale: GPA
    achieved: 4.5
    outOf: 5

```

**Comment by ChapChap** [comment]
So what is required and what is optional ?

**Comment by hossainemruz** [comment]
Sorry guys for being late on this PR. I am relocating. So, I wouldn't be able to work on it for few more days.

**Comment by serverfriendsorg** [comment]
This is an awesome feature! Is there may planned to add a section for certifications? Maybe this can be combined with the education section or so.

**Comment by hossainemruz** [comment]
Yes @serverfriendsorg its already in the project roadmap under `Accomplishments/Courses` section. However, it may take some time.

**Comment by serverfriendsorg** [comment]
> Yes @serverfriendsorg its already in the project roadmap under `Accomplishments/Courses` section. However, it may take some time.

Thanks, this is great. Can't wait to see that feature.

**Comment by achapusot-pass** [comment]
🙌 Yeah

**Comment by ChapChap** [comment]
🙌 Yeah

**Pull request merged**
