### PR TITLE
Added some social buttons to the "Post" template

### PR DESCRIPTION
**Pull request by MarionMoseby**
I have added some (optional) social buttons to the Post template, so that anyone can share the posts

### CODE REVIEW

**Comment by hossainemruz** [comment]
Thank you @MarionMoseby . I will take a look at tomorrow.

**Comment by hossainemruz** [comment]
@MarionMoseby can you please add an example how to use this feature.  Also, a screenshot will be helpful to understand how it looks.

**Comment by MarionMoseby** [comment]
Ok, so, this works like this. If this is your config.yaml (with everything set to yes):

`  SocialButtons:
    facebook: true
    twitter: true
    reddit: true
    tumblr: true
    pocket: true
    linkedin: true
    diaspora: true
    mastodon: true
    whatsapp: true
    email: true`

You get this buttons in each post:

Screenshot_20210910_000106

However, if you change config.yaml to:

`  SocialButtons:
    facebook: true
    whatsapp: true
    email: true`

You only get the corresponding button:

Screenshot_20210910_000206

Each button lets you share the post in the respective social network: if I click whatsapp:

Screenshot_20210910_000342

I get a share prompt:

Screenshot_20210910_000424

Same for reddit:

Screenshot_20210910_000501

The mail icon opens a mailto: prompt:

Screenshot_20210910_000624

I felt like this was a useful functionality. Im sorry I didnt explain myself better, and sorry the screenshots are in spanish hehe

**Comment by hossainemruz** [comment]
Thank you. I will take a look. It may take some time. Please, be patient.

**Comment by MarionMoseby** [comment]
Okay, no rush! Have a nice weekend!
-------- Mensaje original --------

**Review by hossainemruz — APPROVED** [review]
@MarionMoseby I have pushed some new changes. Basically updated the look and feel for the share buttons. Also, updated the location of this share buttons in `config.yaml` file.

Now, you have to provide the share buttons configuration under `site.Prams.features.blog.shareButtons`.

For example,
```yaml
  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true
```

This will help us to keep configuration clean when the theme will be used for different purposes.

**Comment by hossainemruz** [comment]
Try pulling the latest the changes and let me know what do you think.

**Comment by MarionMoseby** [comment]
The changes are cool! The buttons definitely look more in-theme now; although I think I liked better the more colorful version, this can be cool if you prefer it :p 

Only major "issue" is, if you set no "sharebutton", the "improve that page" button appears centered, which looks worse :(

**Comment by MarionMoseby** [comment]
I suggest putting the div outside the {{ if site.Params.features.blog.shareButtons }} condition; that way, it is always generated and the sharebutton floats to the right

**Comment by hossainemruz** [comment]
@MarionMoseby The alignment issue has been fixed. Also, the icons are not using brand color by default. Here, is the new look:
image

**Comment by MarionMoseby** [comment]
Super! I love their look hehe

**Pull request merged**
