### PR TITLE
feat: customMenus in footer

### PR DESCRIPTION
**Pull request by stueja**
Show customMenu links also in footer.
In `config.yaml`,
 - `params.footer.enable` is `true` to show the footer at all
 - `params.footer.navigation.enable` is `true` to show navigation items
   in the footer
 - `params.footer.navigation.customMenus.enable` is `true` to show
   customMenu items

Example:
```
params:
  footer:
    enable: true
    navigation:
      enable: true
      customMenus:
        enable: true
```

In `data/<language>/site.yaml`,
 - `customMenus` must contain at least one entry with `showOnFooter:
   true`

Example:
 ```
 customMenus:
   - name: Imprint
     url: posts/imprint
     showOnFooter: true
 ```

### CODE REVIEW

**Comment by hossainemruz** [comment]
@stueja I think we should avoid another extra layer of nesting in the footer. We can just specify,
```yaml
params:
  footer:
    enable: true
    navigation:
      enable: true
      customMenus: true
```

Also, do we really need `showOnFooter` field in the custom menu entry? Why user might want to keep some menu items hidden in footer where he allowed in navbar?

**Comment by stueja** [comment]
Some items might not be wished in the top navbar, e. g. imprint or GDPR declaration or other. This was my thought.
I had implemented that in my local copy and thought I'd share it with you. But of course it is up to you to decide which PR you want to merge and which one not :)

**Comment by hossainemruz** [comment]
Ok. That's a valid use case. I will review the PR soon. Can you please acknowledge the nesting issue on `footer.navbar.customMenus` ?

>But of course it is up to you to decide which PR you want to merge and which one not :)

Sorry, if I disappoint you. We have to keep balance between features and maintainability. If there are too many moving parts, chances are something will break in every release. That's why we have to decide whether a use-case is worth or not to take the burden.

**Comment by stueja** [comment]
Absolutely no disappointment on my side! I just wanted to say that I don't have hard feelings if a PR is not merged.
I will change the nesting also once I found out how to change a PR.

**Review by Rihoj — APPROVED** [review]
I personally like this change, and it looks like the nested issue mentioned was taken care of. Is there any way we could tie this to a change to https://github.com/hugo-toha/guides and https://toha-guides.netlify.app/posts/configuration/site-parameters/#add-custom-menus to try to keep the documentation up to date?

**Comment by hossainemruz** [comment]
@Rihoj Thank you for reviewing. I am looking for a spare time to update those guides before merging this PR. It would be greatly appreciated if you can send a PR for the guides. I can merge this PR then.

**Review by hossainemruz — APPROVED** [review]

**Pull request merged**
