### PR TITLE
Add analytics template + Add Ko-Fi donation button + Host fonts locally

### LINKED ISSUE #463: Feature Request: adding ko-fi floating button
### Describe the solution you'd like
I want to add Ko-fi floating button: https://ko-fi.com/Manage/donation-widget-setup

### Describe alternatives you've considered
I am not good at web development.

### Additional context
I want to add this: 
```javascript
<script src='https://storage.ko-fi.com/cdn/scripts/overlay-widget.js'></script>
<script>
  kofiWidgetOverlay.draw('kingabzpro', {
    'type': 'floating-chat',
    'floating-chat.donateButton.text': 'Support me',
    'floating-chat.donateButton.background-color': '#5cb85c',
    'floating-chat.donateButton.text-color': '#fff'
  });
</script>
```

### PR DESCRIPTION
**Pull request by MarionMoseby**
### Issue

Fixes #463

### Description

Fixed latex support, added some more analytics methods and removed one CDN. Just some miscellaneous improvements I need for my website.

### Test Evidence

Everything works fine according to FFs HTML inspector

### CODE REVIEW

**Comment by hossainemruz** [comment]
Thank you @MarionMoseby. Looks good to me. I will test and merge soon.

**Comment by MarionMoseby** [comment]
I am sorry, shouldnt the post be added on hugo-toha/guides ?

**Comment by hossainemruz** [comment]
Yes. Updating post on guides repo will be great. [hugo-toha.github.io](https://github.com/hugo-toha/hugo-toha.github.io) serves as example repo for the theme. That's why we need to add the configurations there.

**Comment by MarionMoseby** [comment]
Ok, things updated as suggested. Also added a Ko-Fi floating button in case some user (hehe me) wants to enable support for the blog. Config would be:

`
  features:
    Support:
      enable: true

      # Ko-Fi Floating button
      kofi:
        user: "<user id>"
        text: "Support Me"
        backgroundcolor: "#00b9fe"
        textcolor: "#fff"

`

**Comment by hossainemruz** [comment]
Hi @MarionMoseby, Thank you for the update.

There is a issue with this approach. Since, we have replaced `googleAnalytics` with `features.analytics.google`, we can't use the internal templates anymore. The internal templates require `googleAnalytics` to be on the top level field. We have to find a workaround here.

Don't worry. I will take this PR from here. I will be able to work on this PR probably in next week. Till then, happy weekend.

**Comment by MarionMoseby** [comment]
Ok, thank you so much! Have a nice weekend!

Kind regards :p

**Comment by hossainemruz** [comment]
@MarionMoseby I have updated the PR. Fixed the Google Analytics issue. I have made little change in the configuration format. Now, you have to provide analytics configuration as below.

```yaml
params:
  features:
    # Enable Analytics
    analytics:
      enabled: true
      # Google Analytics
      google:
        id: UA-122321624-2
      # CounterDev
      counterDev:
        id: <your counterdev id>
      # GoatCounter
      goatCounter:
        code: <your goat counter code>
```

This format will help us to introduce further options for the analytics providers in future without breaking backward compatibility.

I have also added the missing font files. Let me know if there is anything remaining for this PR.

**Review by hossainemruz — APPROVED** [review]

**Comment by MarionMoseby** [comment]
Sorry I didn't answer earlier, I find this perfect, and way more elegant than what I wrote! Maybe I would change the GoatCounter thing to id, instead of code, to match the overall style? Also, I see you left the Ko-Fi thingy unchanged, right?

**Comment by hossainemruz** [comment]
>Maybe I would change the GoatCounter thing to id, instead of code, to match the overall style?
I thought about that. The GoatCounter examples used <My Code> in place of the id. So, I assumed they called it code instead of ID. If you think id will be better, feel free to send a PR.

>Also, I see you left the Ko-Fi thingy unchanged, right?
Yes. There is not much configurable options in ko-fi button. I tried to customize it but it didn't worked. So, I left it as it was. Doesn't look that too bad though. :)

**Comment by MarionMoseby** [comment]
Okey hehe its perfect as it is so no worries. Thanks for editing my MR! Updating my theme now... :p

**Pull request merged**
