### PR TITLE
Support providing custom buttons in about section

### LINKED ISSUE #610: [Feature Request] 'Curriculum Vitae' button instead of the 'Resume' button
Hello folks,

This is a very minor feature request, which would be very helpful for researchers.
The current website has a link for one's resume. It would be cool if we can use the word 'Curriculum Vitae' instead of 'Resume' for those in academia.

Thank you.

### PR DESCRIPTION
**Pull request by hossainemruz**
Signed-off-by: hossainemruz <hossainemruz@gmail.com>

### Issue

Fixes #610

### Description

This allow user to provide custom button with resource links. For example, user can use this to provide link of their resume file. This lets user to provide multiple buttons with custom text.

**Usage:**
Add `resourceLinks` section in the `about.yaml` data file.

```yaml
# You can put custom buttons to link your relevant resources.
# For example, you can put link for your resume.
resourceLinks:
- title: Resume
  url: "files/resume.pdf"
```

#### Test Evidence
Screenshot from 2022-07-16 21-49-34

### CODE REVIEW

**Comment by IhnwhiHeo** [comment]
@hossainemruz Thank you so much! A quick question: when I did this, the resume button itself disappeared. 
I did like this:
```
# your resume. this file path should be relative to you "static" directory
resourcelinks:
- title: Resume
  url: "files/cv.pdf" # files directory
# resume: "files/cv.pdf" # files directory
```
where ```# resume: "files/cv.pdf" # files directory``` was the original code. What's wrong with this?

**Comment by hossainemruz** [comment]
You have to update the theme to latest commit.

**Comment by IhnwhiHeo** [comment]
I also updated the theme; this is automatically done by the bot, tho

**Comment by hossainemruz** [comment]
It is `resourceLinks` not `resourcelinks`.

**Comment by IhnwhiHeo** [comment]
Yup, thanks for catching that. I tried but still doesn't work
```
resourceLinks:
- title: Resume
  url: "files/iheo2022july.pdf"
# resume: "files/iheo2022july.pdf" # files directory
```

**Comment by hossainemruz** [comment]
Your site is still using an old theme version. Check the commit hash.

**Comment by IhnwhiHeo** [comment]
Oh, didn't know that. Can you please direct me to the commit hash you mean? Or how can I manually update the version to the latest one?

**Comment by hossainemruz** [comment]
Here are the latest commits: https://github.com/hugo-toha/toha/commits/main

**Comment by IhnwhiHeo** [comment]
Thanks so much! Then how can I manually update this without awaiting the bot?

**Comment by hossainemruz** [comment]
https://stackoverflow.com/questions/5828324/update-git-submodule-to-latest-commit-on-origin?answertab=trending#tab-top

**Comment by IhnwhiHeo** [comment]
Greatly appreciate it!!

**Comment by IhnwhiHeo** [comment]
@hossainemruz The theme has been updated but still, the CV button does not appear. Can you please check?
```
# your resume. this file path should be relative to your "static" directory
resourceLinks:
- title: Resume
  url: "files/cv.pdf"
# resume: "files/cv.pdf" # files directory
```

**Comment by hossainemruz** [comment]
The theme hasn't been updated. It is still using a version from Sept 2, 2021. Can you please check StackOverflow link I have provided and update the theme manually.

**Comment by IhnwhiHeo** [comment]
I greatly appreciate your time and kindness. I merged your PR, removed the local repo, and re-cloned the repository. When I rechecked my website, the 'Resume' button appeared but not the 'Curriculum Vitae' button. So, this does not work. Can you please check it, again? Let me know if I missed anything.

**Comment by hossainemruz** [comment]
You have to change the title to `Curriculum Vitae` here: https://github.com/IhnwhiHeo/ihnwhiheo.github.io/blob/bb904668e4cdb749d368eb6caa890a551cf5ca96/data/en/sections/about.yaml#L19

**Comment by IhnwhiHeo** [comment]
Now this works perfectly! I cannot thank you enough. I appreciate your patience and help!!

**Pull request merged**
