### PR TITLE
Fix google analytics feature

### PR DESCRIPTION
**Pull request by joyao**
### Issue
Fixes https://github.com/hugo-toha/toha/issues/955

### Description

Fix google analytics feature based on official document.
https://gohugo.io/templates/embedded/#google-analytics

### Test Evidence
image

### CODE REVIEW

**Review by hossainemruz — COMMENTED** [review]
Hi @joyao ! Thank you for the PR. Look like we are breaking compatibility here. With this change, following configuration will not work anymore:
```yaml
services:
  googleAnalytics:
    ID: G-MEASUREMENT_ID
```

Do we want to force user to use analytics configuration from `site.Params.analytics.services.google.id` ? In that case, we should also provide a way do specify `respectDoNotTrack` under `site.Params.analytics.services.google` section.

**Comment by joyao** [comment]
> Hi @joyao ! Thank you for the PR. Look like we are breaking compatibility here. With this change, following configuration will not work anymore:
> 
> ```yaml
> services:
>   googleAnalytics:
>     ID: G-MEASUREMENT_ID
> ```
> 
> Do we want to force user to use analytics configuration from `site.Params.analytics.services.google.id` ? In that case, we should also provide a way do specify `respectDoNotTrack` under `site.Params.analytics.services.google` section.

I think both methods should be supported. I’ll fix it and thanks for your suggestion.

**Comment by jamesdeluk** [comment]
So what's the current workaround for getting analytics working, manually having these two files within layouts?

**Comment by joyao** [comment]
> So what's the current workaround for getting analytics working, manually having these two files within layouts?

Hi @jamesdeluk, this PR hasn't been merged yet. If you want to have this fixed feature, you can merge my branch or fix these two files manually in your project.

**Comment by joyao** [comment]
> 
> Thanks. And which is the best `yaml` config of the two above?

This one:

``` yaml
analytics:
  enabled: true
  services:
    # Google Analytics
    google:
      id: G-H4LBG7NDFZ
      respectDoNotTrack: false
```

You don't need to make many changes to this, this section is already in the current hugo.yaml file. You just need to change the id.

**Comment by jamesdeluk** [comment]
> This one:
> 
> ```yaml
> analytics:
>   enabled: true
>   services:
>     # Google Analytics
>     google:
>       id: G-H4LBG7NDFZ
>       respectDoNotTrack: false
> ```
> 
> You don't need to make many changes to this, this section is already in the current hugo.yaml file. You just need to change the id.

Great, thanks! And I guess `respectDoNotTrack` can be set to `true` and it'll still work?

**Comment by joyao** [comment]
> 
> Great, thanks! And I guess `respectDoNotTrack` can be set to `true` and it'll still work?

Yes, it should work. :)

**Comment by joyao** [comment]
Hi @hossainemruz, I believe it works as expected. Please take your time reviewing it. Thank you.

**Review by hossainemruz — APPROVED** [review]

**Pull request merged**
