### PR TITLE
Add company and school logos

### LINKED ISSUE #153: Company name should be on top
### Describe the solution you'd like

When we worked at multiple designations at a single organization, then the company name comes on top and designations are nested inside, but if a single designation is chosen then  Designation is on top and company name is below it.

### Describe alternatives you've considered

I think we should keep the UI consistent with company name on top even if only 1 designation is used for a particular organization, that way the UI looks more consistent and company names looks highlighted even for the single designation company.

Screenshot (28)

### LINKED ISSUE #871: Feature request about section Experiences (show logo company)
Hi @hossainemruz 

After all the work done on Toha v4, I think, it's time to make evolution on the frontend of Toha. 

So, first, i closed my initial issue #827. Because, i'm not satisfy about the content of this issue, and I'm not an developer. I feel not be able to dev this feature. So, i make this new issue with more explications here for any people.

### Definition of Ready

I would like to have the possibility to add the logos of the companies where I worked in the `Experience` section. I've put an example below that describes the imagined presentation, and I've also added some sample code that might meet this need.

toha_logo_feature

I post the code showed in the image to make it clearer.

```yaml
experiences:
  - company:
      name: Example.co
      logo: image/experience/logo.example.co.jpg
      url: https://www.example.co
      location: Washington DC
  - positions:
      designation: Software engineer
      start: Mar 2016
      end: May 2017
```
The idea is : 
* We add the path of the logo image for each experience section added in the `experience.yaml` file.
* We add the image in `asset/sections/experiences/` directory.

### Definition of Done

- [ ] Feature delivered
- [ ] Experience Guide updated

What do you think ?

### PR DESCRIPTION
**Pull request by BernatBC**
### Issue
Fixes #871 
Fixes #153 

### Description
Add logos for the following sections:

- [x] Education
- [x] Experiences

### Test Evidence

image

### CODE REVIEW

**Comment by BernatBC** [comment]
This is how the experiences section will look:
image

**Comment by BernatBC** [comment]
I think now it's better:
image

**Comment by hossainemruz** [comment]
The timeline should be scoped with the position not the company. You can have multiple positions within one company.

**Comment by BernatBC** [comment]
Maybe is this better?
image

**Comment by BernatBC** [comment]
@hossainemruz now it's ready, you can ask for some changes if you wish

**Comment by niltied** [comment]
Great for me. Congrat @BernatBC ! 😀
Thank !

**Comment by niltied** [comment]
Re @hossainemruz & @BernatBC,

For later : don't forget too update **experiences** and **educations** guides (english, spanish and french) about the new field for `experiences.yaml` and `education.yaml`.

**Comment by BernatBC** [comment]
@niltied yesterday I made a Pull Request with these changes. PR: hugo-toha/guides/pull/272

**Comment by BernatBC** [comment]
On top, we can see a multiple-position company, and at the bottom a single-position company. Do you think that we can remove the single position layout and just use the multiple one for both cases?

image

**Comment by niltied** [comment]
Hi @BernatBC, it's fun. I can' wait to deploy this on my website !

**Comment by hossainemruz** [comment]
>On top, we can see a multiple-position company, and at the bottom a single-position company. Do you think that we can remove the single position layout and just use the multiple one for both cases?

Exactly that what I was thinking. Just need to be careful that we don't break any existing site.

**Review by hossainemruz — APPROVED** [review]

**Pull request merged**
