### PR TITLE
feat: configurable custom navbar items

### PR DESCRIPTION
**Pull request by stueja**
The customMenu item from `data/<language>/site.yaml` will only appear if
its property `showOnNavbar` is `true`.

Example:
```
customMenus:
  - name: Imprint
    url: posts/imprint
    showOnNavbar: false
```

### CODE REVIEW

**Comment by hossainemruz** [comment]
@stueja Can you please explain why it is necessary?

**Comment by stueja** [comment]
It might make more sense to see this change in conjunction with #513. 
If you want to see a custom url "Imprint" in the footer but not in the navbar, you'd now have the chance to.
Without this change, all or no custom urls would appear.

**Comment by hossainemruz** [comment]
Ok. I got it.

Btw, we should not change the default behavior. By default, a nav item should be visible in both top navbar and footer. Then, user can use special configuration to hide it from the navbar. Otherwise, it will breaks all the existing user's site.

We can use something like this:
```yaml
customMenus:
  - name: Imprint
    url: posts/imprint
    hideFromNavbar: true
```

**Comment by stueja** [comment]
That's a good point! I would change it accordingly in the PR for the footer then.

**Review by hossainemruz — APPROVED** [review]

**Pull request merged**
