### PR TITLE
Add section to feature some posts in the main page

### PR DESCRIPTION
**Pull request by BernatBC**
### Description
I've made a new section similar to `recent posts` where you can select individually which posts are shown. For example, if I wanted to show the posts with the titles `Europoly`, `Object Tracker` and `Planification project`, the config file will be the following:

```yaml
section:
  name: Working on # Title of section (default: "")
  id: working-on # url id/slug of section *Required*
  enable: true # Boolean to determine if this section is enabled (default: false)
  weight: 6 # Order to display section in (default: alphabetical followed by weight)
  showOnNavbar: true # Boolean to determine if a link should be shown for this section on the navbar
  hideTitle: false # Can optionally hide the title in sections (default: false)

# posts to feature
posts:
  - Europoly
  - Object Tracker
  - Planification project
```

And the result  is the one in the `Test Evidence`.

Also, the name of the section fits my needs, but can be renamed to something like `featured posts`. Tell me if I have to rename the section, if I have to add it to `example site` and `hugo-toha.github.io` (and which posts to feature).

### Test Evidence

image

### CODE REVIEW

**Review by hossainemruz — COMMENTED** [review]
Hi @BernatBC! Thank you for the PR. It is a good idea to have user customizable post list to feature on home page.

There is two problem with this PR.
1. It will not work for multi-language site.
2. We can not control the order which this pages will be shown.

My suggestion will is:
- Let's provide a list of page path instead of page title
- Loop through the list of page paths instead of all regular pages.
- Use [.GetPage](https://gohugo.io/functions/getpage/#getpage-and-multilingual-sites) method to get the page.

Also, please rename the file into `featured-posts.html`.

**Comment by BernatBC** [comment]
Know it should work (at least works in my website). Now the config file is the following:

```yaml
section:
  name: Featured Posts# Title of section (default: "")
  id: featured-posts # url id/slug of section *Required*
  enable: true # Boolean to determine if this section is enabled (default: false)
  weight: 6 # Order to display section in (default: alphabetical followed by weight)
  showOnNavbar: true # Boolean to determine if a link should be shown for this section on the navbar
  hideTitle: false # Can optionally hide the title in sections (default: false)

# posts to feature
posts:
  - europoly
  - objecttracker
  - planificationproject
```

**Review by hossainemruz — APPROVED** [review]
Thank you @BernatBC. Looks good now. Can you please add example in [hugo-toha.github.io](https://github.com/hugo-toha/hugo-toha.github.io)?

**Comment by BernatBC** [comment]
Are there any posts you want to feature? Or I feature `Introduction` and `Rich Content`?

**Comment by hossainemruz** [comment]
Just feature any three.

**Pull request merged**
