### PR TITLE
Added default theme

### PR DESCRIPTION
**Pull request by joyao**
[Updated]
### Issue
Add a new theme feature and fully resolved issues #931 and #934.

### Description
As a developer, I want to be able to customize the theme of my website so that users can have a better browsing experience.

Changes:
1. Gets the default theme values ​​from the site configuration file and leaves the user with the option to change them.
2. If no value is set, the value 'system' is used.

### Test Evidence

| Description                                                                                         | Expected              | Result                | Status |
| --------------------------------------------------------------------------------------------------- | --------------------- | --------------------- | ------ |
| comment out darkMode and theme settings                                                             | light                 | light                 | Pass   |
| comment out theme settings &<br>disable darkMode                                                    | light                 | light                 | Pass   |
| comment out theme settings &<br>enable darkMode                                                     | system                | system                | Pass   |
| comment out darkMode settings &<br>enable theme without service settings                            | system                | system                | Pass   |
| comment out darkMode settings &<br>disable theme settings                                           | light                 | light                 | Pass   |
| comment out darkMode settings &<br>enable theme service default settings                            | system                | system                | Pass   |
| comment out darkMode settings &<br>enable theme settings & set light = false                        | dark                  | dark                  | Pass   |
| comment out darkMode settings &<br>enable theme settings & set dark = false                         | light                 | light                 | Pass   |
| comment out darkMode settings &<br>enable theme settings & set default = light                      | light                 | light                 | Pass   |
| comment out darkMode settings &<br>enable theme settings & set default = dark                       | dark                  | dark                  | Pass   |
| comment out darkMode settings &<br>enable theme settings<br>set light = false & set default = light | dark                  | dark                  | Pass   |
| comment out darkMode settings &<br>enable theme settings<br>set dark = false & set default = dark   | light                 | light                 | Pass   |
| enable darkMode settings &<br>enable theme settings                                                 | follow theme settings | follow theme settings | Pass   |

### CODE REVIEW

**Comment by hossainemruz** [comment]
Hi @joyao! Thank you for the PR. It looks good. I was just wondering if we should combine the theme options under single configuration instead of splitting into `defaultTheme` and `darkMode`?

I was thinking something like this:

```yaml
params:
  features:
    theme:
      light: true # enable light theme. default "true"
      dark: true # enable dark theme. default "true"
      defaultTheme: light # can be either light, dark or system. default "system"
```
What do you think? This will require more work but I can update your PR. We also have to keep backward compatibility.

**Comment by joyao** [comment]
Hi @hossainemruz, that’s a good point and I agree with you. I can try to update if you're not in a hurry. Please let me know your thoughts.

**Comment by hossainemruz** [comment]
> Hi @hossainemruz, that’s a good point and I agree with you. I can try to update if you're not in a hurry. Please let me know your thoughts.

That would be great! Go ahead with the change. Just make sure we are not breaking existing sites.

**Comment by joyao** [comment]
> > Hi @hossainemruz, that’s a good point and I agree with you. I can try to update if you're not in a hurry. Please let me know your thoughts.
> 
> That would be great! Go ahead with the change. Just make sure we are not breaking existing sites.

For sure. This is the unchanging rule. :)

**Comment by joyao** [comment]
Hi @hossainemruz, features and comments have been updated based on what was discussed previously. Please check.

**Comment by hossainemruz** [comment]
> Hi @hossainemruz, features and comments have been updated based on what was discussed previously. Please check.

Thank you @joyao! I will take a look whenever get some time. Thank you for the amazing work.

**Review by hossainemruz — APPROVED** [review]
Thank you @joyao! Looks good now.

**Pull request merged**
