### PR TITLE
Add support for canonical links

### PR DESCRIPTION
**Pull request by davidgs**
### Issue
Fixes https://github.com/hugo-toha/toha/issues/1000

### Description

Add support for canonical links in frontmatter. If you post to an external site, and *also* want to post to your own site, you **must** use a `<link rel="canonical" ` in the header or search engines will refuse to index it (on either site!)

### Test Evidence
canonical1

canonical2

### CODE REVIEW

**Comment by hossainemruz** [comment]
HI @davidgs! Thank you for the PR. If I understand it correctly, this only necessary for post pages right? In that case, I will recommend to add it here:
https://github.com/hugo-toha/toha/blob/bc67ca11873afe2165e6b08cf38dd5e3a3fa735f/layouts/_default/single.html#L2

There is no need to separate this single line into a partial template.

**Comment by davidgs** [comment]
As long as that works, I'm happy! Just having `real canonical` working is a win!

**Comment by davidgs** [comment]
Works just fine. Moved to `single.html` and removed `canonical.html` and the code in `based.html`

**Review by hossainemruz — APPROVED** [review]
Thank you @davidgs

**Pull request merged**
