### PR TITLE
Make search multilingual

### PR DESCRIPTION
**Pull request by MarionMoseby**
### Issue
Fixes [#249](https://github.com/hugo-toha/toha/issues/249)

### Description

This commit makes the search system multilingual. An additional search.langcode.md file must be created for each language the theme supports, so that the search.html template can automatically appear any time a new language is added. I have only added search.es.md because it is my mother tongue, as a demonstration.

### CODE REVIEW

**Comment by hossainemruz** [comment]
Thank you @MarionMoseby . I will review as soon as possible. Currently, I am on a vacation.

**Comment by MarionMoseby** [comment]
Hey! I hope you are having a great vacation, no rush on the MR hehe. I have now added support for custom flags, which should fix [#159](https://github.com/hugo-toha/toha/issues/159) by adding a new configurable parameter, "flag", in the language settings in config,yaml. What I dont understand is why, when I download the theme, by cloning the repo to edit it, it still has countryflags.io as a dependency instead of using the locally downloaded ones, as was enforced in [#298](https://github.com/hugo-toha/toha/pull/298)

**Comment by hossainemruz** [comment]
I have fixed the flag issue in #316

**Review by hossainemruz — APPROVED** [review]
@MarionMoseby I have added `search.md` file for all the available translations. Really appreciating your work. Thank you. 👍🏼

**Pull request merged**
