### PR TITLE
Added Azerbaijan language

### PR DESCRIPTION
**Pull request by KhanbalaRashidov**

### CODE REVIEW

**Comment by BernatBC** [comment]
Hi @KhanbalaRashidov, thank you for the contribution. You can add the language in the [Readme](https://github.com/hugo-toha/toha/blob/main/README.md), in the section where all available languages are listed.

**Comment by KhanbalaRashidov** [comment]
> Hi @KhanbalaRashidov, thank you for the contribution. You can add the language in the [Readme](https://github.com/hugo-toha/toha/blob/main/README.md), in the section where all available languages are listed.

Okay

**Review by BernatBC — APPROVED** [review]
Thank you @KhanbalaRashidov

**Comment by hossainemruz** [comment]
@BernatBC you should have permission to merge the PR. If you don't have, please let me know.

**Comment by BernatBC** [comment]
Got it, thanks @hossainemruz

**Comment by hossainemruz** [comment]
Click that checkbox before automerge button. Then, you will see the merge option.
image

**Comment by BernatBC** [comment]
Hi @hossainemruz, I'm unable to see this checkbox, even after pressing "Enable auto-merge".
Thank you once again!
image
image

**Pull request merged**
