### PR TITLE
Migrate to Bootstrap 5

### LINKED ISSUE #906: Bootstrap 5
### Describe the solution you'd like

Migrate to Bootstrap 5.

### Additional context

This theme looks not bad, but could be even better if it will be upgraded to latest Bootstrap 5.

Btw, link to roadmap is broken.

### PR DESCRIPTION
**Pull request by BernatBC**
### Issue
Fixes #906 

### Description
Migrate Bootstrap 4 to 5.

I've done some testing, but there might be something odd (specially if the config is different than hugo-toha.github.io). If anyone finds some bugs, please tell me.

### CODE REVIEW

**Comment by hossainemruz** [comment]
Thank you @BernatBC! I will take a look soon. From checking the deploy preview, look like the drop downs are not working.

**Comment by BernatBC** [comment]
Looks like I forgot to update Bootstrap to 5 in the example site. Now it should work.

**Comment by BernatBC** [comment]
For some reason it's not working in the preview, but it's fine locally.

**Review by hossainemruz — APPROVED** [review]

**Comment by hossainemruz** [comment]
> For some reason it's not working in the preview, but it's fine locally.

Apparently, you forgot to update `package.hugo.json` which is used to generate `package.json` for the sites that uses this theme.

**Pull request merged**
