### PR TITLE
Add publication section

### LINKED ISSUE #617: Feature Request: Section Publication
### Describe the solution you'd like
Please provide the section: publication too and its corresponding files. I tried my own, but my begineer experties are not working for now.

### Additional context

here in [README.md](https://github.com/hugo-toha/toha), it is mentioned about the publication section. But it is not been checklisted. So, I request to make the necessary changes and update the repository.

### PR DESCRIPTION
**Pull request by hossainemruz**
Signed-off-by: hossainemruz <hossainemruz@gmail.com>

### Issue

Issues:
- https://github.com/hugo-toha/toha/issues/127
- https://github.com/hugo-toha/toha/issues/617

Closes #617

### CODE REVIEW

**Comment by mangla-sarvesh** [comment]
clicking on Category filter is not working.

**Comment by hossainemruz** [comment]
How did you check? Can you share the YAML for publication that you have used?

**Comment by mangla-sarvesh** [comment]
I have downloaded the branch **publication**_ and replaced the files with ./themes/toha/

**This is the yaml file I have used** 

```
# section information
section:
  name: Publications
  id: publications
  enable: true
  weight: 5
  showOnNavbar: true
  # Can optionally hide the title in sections
  # hideTitle: true


# filter buttons
buttons:
- name: All
  filter: "all"
- name: "Machine Learning"
  filter: "machinelearning"
- name: "Image Processing"
  filter: "image-processing"
- name: Security
  filter: "security"

# your publications
publications:
- title: An Example Paper on Machine Learning
  publishedIn:
    name: 2020 IEEE Region Symposium (TENSYMP)
    date: 7 June 2020
    url: https://example.com
  authors:
  - name: Dr. Madman
    url: https://example.com
  - name: Dr. Lessmad
    url: https://example.com
  - name: Dr. Moremad
    url: https://example.com
  - name: Dr. Goodman
    url: https://example.com
  paper:
    summary: Voluptate in id id voluptate laboris. Minim mollit aliquip sit aliqua ut exercitation voluptate eiusmod consequat pariatur sunt enim veniam. Velit esse tempor laboris anim tempor officia. Magna non labore duis do esse sit do ipsum culpa. Officia consequat id non duis culpa dolor. Excepteur magna non nostrud cupidatat aute aliqua aliquip.
    url: https://example.com
  categories: ["machinelearning","image-processing"]
  tags: ["Machine Learning", "Autonomous Driving", "Computer Vision"]

- title: An Sample Paper on Image Processing
  publishedIn:
    name: 2020 IEEE Region Symposium (TENSYMP)
    date: 7 June 2020
    url: https://example.com
  authors:
  - name: Dr. Madman
    url: https://example.com
  - name: Dr. Lessmad
    url: https://example.com
  - name: Dr. Moremad
    url: https://example.com
  - name: Dr. Goodman
    url: https://example.com
  paper:
    summary: Ullamco magna minim cupidatat Lorem ea ex aliqua fugiat et. Dolor quis cillum ea duis irure et commodo aliquip consectetur ullamco labore ut anim nisi. Commodo reprehenderit est consectetur tempor adipisicing occaecat exercitation amet do aliquip dolor do irure. Labore officia ut magna pariatur reprehenderit et ex sit sunt. Magna proident ullamco adipisicing sit.
    url: https://example.com
  categories: ["image-processing"]
  tags: ["Image Processing", "Computer Vision"]

- title: An Example Paper on Security
  publishedIn:
    name: 2020 IEEE Region Symposium (TENSYMP)
    date: 7 June 2020
    url: https://example.com
  authors:
  - name: Dr. Madman
    url: https://example.com
  - name: Dr. Lessmad
    url: https://example.com
  - name: Dr. Moremad
    url: https://example.com
  - name: Dr. Goodman
    url: https://example.com
  paper:
    summary: Dolor ad cupidatat pariatur nulla ipsum ex ullamco nisi anim ullamco. Dolore elit esse in exercitation minim aliqua. Amet velit incididunt magna laboris. Proident reprehenderit deserunt ad officia duis dolor. Tempor nostrud ullamco ullamco sint deserunt cupidatat irure minim consectetur nulla adipisicing sunt.
    url: https://example.com
  categories: ["security"]
  tags: ["Machine Learning", "Autonomous Driving", "Machine Vision"]
```

**Comment by hossainemruz** [comment]
>clicking on Category filter is not working.

I can see it is working on your site. What issue are you facing actually? By `Category filter` did you mean tags?

**Pull request merged**
